### ISSUE TITLE
Output to html is giving self not defined.

### ISSUE THREAD

**Issue by Sreemanth** [ashima/pdf-table-extract#16]
$ pdf-table-extract -i A1.pdf -o a1.html -p 1 -t table_html
global name 'self' is not defined

**Comment by eelsirhc** [comment]
I think this is now fixed. There were old 'self.' object references in the html table output code.

**Comment by eelsirhc** [comment]
pushed in 50760ea, but the error message you got wasn't very helpful for identifying the bug. Changeset 7a04fc5 adds a --traceback option to make the error more verbose (messier, but identifies the correct line).
