### ISSUE TITLE
Unclear failure mode if pdftoppm not installed

### ISSUE THREAD

**Issue by cancan101** [ashima/pdf-table-extract#9]
When `pdftoppm` is not installed, pdf-table-extract fails:

```
----> 1 pdf.process_page("foo.pdf", "1")

/usr/lib/python2.7/site-packages/pdf_table_extract-0.1-py2.7.egg/pdftableextract/core.pyc in process_page(infile, pgs, outfilename, greyscale_threshold, page, crop, line_length, bitmap_resolution, name, pad, white, black, bitmap, checkcrop, checklines, checkdivs, checkcell)
     54 # image load secion.
     55
---> 56   (maxval, width, height, data) = readPNM(p.stdout)
     57
     58   pad = int(pad)

/usr/lib/python2.7/site-packages/pdf_table_extract-0.1-py2.7.egg/pdftableextract/pnm.pyc in readPNM(fd)
     20   data = fd.read()
     21
---> 22   xs, ys = s.split()
     23   width = int(xs)
     24   height = int(ys)

ValueError: need more than 0 values to unpack
```

**Comment by eelsirhc** [comment]
`pdftoppm` is a requirement for the code to work. It's noted in the README.

Try it with the latest update, which will happily throw an OSError at you if pdftoppm or pdftotext doesn't exist. If you give it an empty file, it will raise in I/O error at the same point (~pnm.py line 22) but an empty file isn't the only reason this error occurs. Subprocess doesn't raise exceptions when the executable exists but produces an error (even if the executable intentionally returns the error) which makes detecting errors in the subprocess call difficult.
